version: "3"
services:

  mongodb:
    image: mongo
    container_name: mongodb-container
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
    ports:
      - 27017:27017


  zipkin:
    image: openzipkin/zipkin
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
    
    environment:
      - SELF_TRACING_ENABLED=true
    ports:
    
      - 9411:9411
    depends_on:
      - mongodb
  customer-api:
    build: ./MicroServiceSimple-Customer
    image: customer-api
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
    ports:
      - 7001:7001
      - 8001:8001
    depends_on:
      - zipkin
      - mongodb

      
  vehicle-api:
    build: ./MicroServiceSimple-Vehicle
    image: vehicle-api
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
    ports:
      - 7002:7002
      - 8002:8002      
    depends_on:
      - zipkin
      - mongodb
      

      
  vehicleowner-api:
    build: ./MicroServiceSimple-VehicleOwner
    image: vehicleowner-api
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
    ports:
      - 7003:7003
      - 8003:8003      
    depends_on:
      - zipkin
      - mongodb
      

      
  dashboard-api:
    build: ./MicroServiceSimple-Dashboard
    image: dashboard-api
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
    environment:
      NODE_ENV : docker    
    ports:
      - 7004:7004
      - 8004:8004      
    depends_on:
      - zipkin
      - mongodb
      

       
  pulsworker-api:
    build: ./MicroServiceSimple-Pulsworker
    image: pulsworker-api
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
    environment:
      NODE_ENV : docker    
    ports:
      - 7005:7005
      - 8005:8005      
    depends_on:
      - zipkin
      - mongodb
      - vehicleowner-api
      
